# This action should be kept in sync with
# https://github.com/hanzoui/studio_frontend/blob/main/.github/workflows/test-ui.yaml

name: Test Hanzo Frontend

on:
  workflow_dispatch:
    inputs:
      frontend-branch:
        description: "Frontend branch"
        required: true
        default: "main"

  push:
    branches: [main, master]
    paths-ignore:
      - ".cursor/**"
      - ".husky/**"
      - ".vscode/**"
      - ".github/ISSUE_TEMPLATE/**"
      - "test/**"

  pull_request:
    branches: [main, master]
    paths-ignore:
      - ".cursor/**"
      - ".husky/**"
      - ".vscode/**"
      - ".github/ISSUE_TEMPLATE/**"
      - "test/**"

jobs:
  test-hanzo-studio-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout litegraph
        uses: actions/checkout@v4
        with:
          path: "litegraph"

      - name: Checkout Hanzo Studio
        uses: actions/checkout@v4
        with:
          repository: "hanzoai/studio"
          path: "Hanzo Studio"
          ref: master

      - name: Checkout Hanzo Studio_frontend
        uses: actions/checkout@v4
        with:
          repository: "hanzoui/studio_frontend"
          path: "Hanzo Studio_frontend"
          ref: ${{ inputs.frontend-branch }}

      - name: Checkout Hanzo Studio_devtools
        uses: actions/checkout@v4
        with:
          repository: "hanzoui/studio_devtools"
          path: "Hanzo Studio/custom_nodes/Hanzo Studio_devtools"

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
          pip install wait-for-it
        working-directory: Hanzo Studio

      - name: Build litegraph
        run: |
          npm ci
          npm run build
        working-directory: litegraph

      - name: Install updated litegraph in Hanzo Studio_frontend
        run: |
          npm ci
          npm install ../litegraph
          npm run build
        working-directory: Hanzo Studio_frontend

      - name: Start Hanzo Studio server
        run: |
          python main.py --cpu --multi-user --front-end-root ../Hanzo Studio_frontend/dist &
          wait-for-it --service 127.0.0.1:8188 -t 600
        working-directory: Hanzo Studio

      - name: Run UI tests
        run: |
          npm run test:component
          npm run test:unit
        working-directory: Hanzo Studio_frontend

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
        working-directory: Hanzo Studio_frontend

      - name: Run Playwright tests (chromium)
        run: npx playwright test --project=chromium
        working-directory: Hanzo Studio_frontend

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: Hanzo Studio_frontend/playwright-report/
          retention-days: 30
